### ISSUE TITLE
does it also force http\https only?

### ISSUE THREAD

**Issue by boynet** [OwenMelbz/domain-enforcement#2]
does it also force http\https only?
and also no license file

**Comment by OwenMelbz** [comment]
Yes - it can do.

It enforces what ever is in your `APP_ENV` 

So if you have

```
APP_ENV="https://mywebsite.com"
```

it will enforce https

if you have 

```
APP_ENV="http://mywebsite.com"
```

it will remove https

**Comment by boynet** [comment]
Thanks, I already did it in all my project, but your solution is better :) can I ask for license? no info about it

**Comment by OwenMelbz** [comment]
You can do whatever you like with it, except steal and brand as your own :D

**Comment by boynet** [comment]
you need [WTFPL](http://www.wtfpl.net/about/)

>   DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
>                     Version 2, December 2004 
> 
>  Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 
> 
>  Everyone is permitted to copy and distribute verbatim or modified 
>  copies of this license document, and changing it is allowed as long 
>  as the name is changed. 
> 
>             DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
>    TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 
> 
>   0. You just DO WHAT THE FUCK YOU WANT TO.
